#!/usr/bin/env bash
# Record which libkrun/libkrunfw submodule commits the bundled libs in a given
# lib dir were built from. Called by the libkrun build scripts after they copy
# fresh binaries into place, so the committed lib/ always carries proof of which
# source it came from. check-libkrun-provenance.sh later verifies this matches
# the pinned submodules — that's what stops a stale binary from shipping.
#
# Usage: stamp-libkrun-provenance.sh <lib-dir> [--skip-libkrunfw]
#   <lib-dir>          e.g. lib, lib/linux-x86_64, lib/linux-aarch64
#   --skip-libkrunfw   keep the existing libkrunfw= line (the build reused the
#                      committed libkrunfw.* instead of rebuilding it)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB_DIR="${1:?usage: stamp-libkrun-provenance.sh <lib-dir> [--skip-libkrunfw]}"
SKIP_FW=0
[[ "${2:-}" == "--skip-libkrunfw" ]] && SKIP_FW=1

cd "$REPO_ROOT"
PROV="$LIB_DIR/libkrun.provenance"
mkdir -p "$LIB_DIR"

# The commit each submodule is actually checked out at right now (what we built).
krun_sha="$(git -C libkrun rev-parse HEAD)"

if [[ "$SKIP_FW" == "1" && -f "$PROV" ]]; then
  fw_sha="$(grep '^libkrunfw=' "$PROV" | cut -d= -f2)"
else
  fw_sha="$(git -C libkrunfw rev-parse HEAD)"
fi

cat > "$PROV" <<EOF
# Auto-generated by scripts/stamp-libkrun-provenance.sh — do not edit by hand.
# The libkrun/libkrunfw submodule commits the bundled libs in this dir were
# built from. Verified against the pinned submodules by
# scripts/check-libkrun-provenance.sh (run in CI).
libkrun=$krun_sha
libkrunfw=$fw_sha
EOF

echo "stamped $PROV (libkrun=$krun_sha libkrunfw=$fw_sha)"
